##### This is an example .yaml file for how you should make your config file
##### See below for what you need to have
##### Make sure the paths are correct. They are individual to your machine
randomseed: 0
device: "cuda"
dataset:
  forcing_path: "/home/fzr5082/PGML_STemp_results/inputs/forcing99_synth_T_2010_new2.feather" #forcing50_synth_T_2010.feather" #"/home/fzr5082/GitHub2/LSTM_temp2/scratch/SNTemp/Forcing/Forcing_new/forcing_99%_days_99sites.feather"
  attr_path: "/home/fzr5082/PGML_STemp_results/inputs/attr_temp99%_days_99sites.feather" #attr50_synth_T_2010.feather"
output:
  model: "//home//fzr5082//PGML_STemp_results//models"
  data: "//home//fzr5082//PGML_STemp_results//data"

optData:
  name: 'hydroDL.data.camels.DataframeCamels'
  subset: 'All'
  varT: ['dayl(s)', 'prcp(mm/day)', 'tmax(C)', 'tmin(C)', 'vp(Pa)','srad(W/m2)', '00060_Mean']
  varC: [
    'DRAIN_SQKM', 'STREAMS_KM_SQ_KM', 'STOR_NID_2009', 'FORESTNLCD06',
    'PLANTNLCD06', 'SLOPE_PCT', 'RAW_DIS_NEAREST_MAJ_DAM', 'PERDUN',
    'RAW_DIS_NEAREST_DAM', 'RAW_AVG_DIS_ALL_MAJ_DAMS', 'T_MIN_BASIN',
    'T_MINSTD_BASIN', 'RH_BASIN',  'RAW_AVG_DIS_ALLDAMS', 'PPTAVG_BASIN',
    'HIRES_LENTIC_PCT','T_AVG_BASIN', 'T_MAX_BASIN','T_MAXSTD_BASIN',
    'NDAMS_2009', 'ELEV_MEAN_M_BASIN'
  ]
  target: ['synth_shade_0130365']   #['synth_T_0520180']
  tRange: [20101001, 20161001]
  t_train: [20111001, 20161001]
  t_val: [20151001, 20161001]
  t_test: [20141001, 20161001]
  doNorm: [True, True]
  rmNan: [True, False]
  daObs: 0
  damean: False
  davar: 'streamflow'
  dameanopt: 0
  lckernel: None
  fdcopt: False
hyperparameters:
  rho: 360
  batch_size: 50
  EPOCHS: 400
  hidden_size: 60
  dropout: 0.5
  saveEpoch: 100
seq_lin_layers:
  hidden_size: 60
params_target: ["res_time_srflow", "res_time_ssflow", "res_time_gwflow"]
one_param_target: ["shade_fraction"]
STemp_default_params:
  shade_fraction: 0.05
  longwave_reflect_fraction: 0.1
  cloud_fraction: 0.1
  emissivity_veg: 0.9526
  shade_fraction_riparian: 0.5
  albedo: 0.1
  delta_Z: 1.0       # for streambed conduction
params:
  water_density: 1000
  C_w: 4184    # J/kg. K
initial_values:
  shade_fraction: 0.1
no_basins: 99
