##### This is an example .yaml file for how you should make your config file
##### See below for what you need to have
##### Make sure the paths are correct. They are individual to your machine
randomseed: [0]   # None means random
Action: [0, 1]   # 0:Train,   1: Test
device: "cuda"
nmul: 16
#forcing_path: "//storage//work//fzr5082//PGML_STemp_results//inputs//forcing_415_tmean_ccov_fillNa.feather" #          no_dam_forcing_99%_days34sites.feather
#attr_path: "//storage//work//fzr5082//PGML_STemp_results//inputs//attr_415_tmean_ccov.feather" #           no_dam_attr_temp99%_days34sites.feather
forcing_path: "G:\\Farshid\\PGML_STemp_results\\inputs\\inputs_2003\\forcing_415_tmean_ccov_fillNa.feather" #        forcing_10%_days_415sites_ccov.feather  no_dam_forcing_99%_days34sites.feather
attr_path: "G:\\Farshid\\PGML_STemp_results\\inputs\\inputs_2003\\attr_415_tmean_ccov.feather" #        camels_40_attr.feather  no_dam_attr_temp99%_days34sites.feather
output_model: "G:\\Farshid\\fzr5082\\PGML_STemp_results\\models\\415_sites_new2"
data: "//home//fzr5082//PGML_STemp_results//data"


name: 'hydroDL.data.camels.DataframeCamels'
subset: 'All'
varT_NN: ['dayl(s)', 'prcp(mm/day)', 'tmax(C)', 'tmin(C)', 'vp(Pa)','srad(W/m2)', '00060_Mean']

varC_NN: [
  'ELEV_MEAN_M_BASIN',  'ELEV_STD_M_BASIN',
  'SLOPE_PCT', 'DRAIN_SQKM', 'NDAMS_2009', 'MAJ_NDAMS_2009',
  'FRAGUN_BASIN', 'FORESTNLCD06',  'AWCAVE', 'PERMAVE', 'BDAVE',
  'ROCKDEPAVE', 'CLAYAVE', 'SILTAVE', 'SANDAVE', 'HGA', 'HGB',
  'HGC', 'HGVAR', 'HGD', 'PPTAVG_BASIN', 'SNOW_PCT_PRECIP',
  'PRECIP_SEAS_IND', 'T_AVG_BASIN',  'T_MAX_BASIN',
  'T_MAXSTD_BASIN', 'RH_BASIN',
  'GEOL_REEDBUSH_DOM_PCT', 'GEOL_REEDBUSH_DOM',
   'HIRES_LENTIC_PCT', 'PERDUN', 'PERHOR', 'RIP100_FOREST'
]

varT_SNTEMP: [
               'tmax(C)', 'tmin(C)','dayl(s)', "t_monthly(C)", "ccov", 'prcp(mm/day)', 'vp(Pa)', "srad(W/m2)",
               '00060_Mean'
]
varC_SNTEMP: [
               "stream_length_square", 'PPTAVG_BASIN', 'SLOPE_PCT',
                'ELEV_MEAN_M_BASIN', "RIP100_FOREST", # "NHDlength_tot(m)"
]
varT_PRMS: [
  'prcp(mm/day)', 'tmax(C)', 'tmin(C)', "t_monthly(C)", 'dayl(s)'
]

varC_PRMS: [
  'ELEV_MEAN_M_BASIN',  'ELEV_STD_M_BASIN',
  'SLOPE_PCT', 'DRAIN_SQKM', 'NDAMS_2009', 'MAJ_NDAMS_2009',
  'FRAGUN_BASIN', 'FORESTNLCD06',  'AWCAVE', 'PERMAVE', 'BDAVE',
  'ROCKDEPAVE', 'CLAYAVE', 'SILTAVE', 'SANDAVE', 'HGA', 'HGB',
  'HGC', 'HGVAR', 'HGD', 'PPTAVG_BASIN', 'SNOW_PCT_PRECIP',
  'PRECIP_SEAS_IND', 'T_AVG_BASIN',  'T_MAX_BASIN',
  'T_MAXSTD_BASIN', 'RH_BASIN',
  'GEOL_REEDBUSH_DOM_PCT', 'GEOL_REEDBUSH_DOM',
  'HIRES_LENTIC_PCT', 'PERDUN', 'PERHOR', 'RIP100_FOREST'
]

target: [ "00010_Mean"]     # ['synth_T_1030365']   #   #     #['synth_shade_0130365']   ['synth_T_0520180']
tRange: [19800101, 20230101]
t_train: [20101001, 20141001]   # there should be an overlap because of the warm_up
t_val: [20101001, 20111001]
t_test: [20131001, 20161001]    # there should be an overlap because of the warm_up
doNorm: [True, False]
rmNan: [True, False]
daObs: 0
damean: False
davar: 'StreamTemp'
dameanopt: 0
lckernel: None
fdcopt: False

rho: 365
batch_size: 208
EPOCHS: 300
hidden_size: 256
dropout: 0.5
saveEpoch: 50

seq_lin_layers_hidden_size: 256

res_time_type: "Meisner"   #"van Vliet"  # "van Vliet", "Meisner", "SNTEMP"
res_time_lenF_ssflow: 30   #60
res_time_lenF_gwflow: 365 #
res_time_lenF_srflow: 1
lat_temp_adj: False
shade_smoothening: False

frac_smoothening_mode: False
frac_smoothening_gw_filter_size: 40
frac_smoothening_ss_filter_size: 30
warm_up: 365
make_sr_masked_by_precip: "False"
params_target: ["res_time_srflow", "res_time_ssflow", "res_time_gwflow"]
one_param_target: ["shade_fraction"]
STemp_default_shade_fraction: 0.05
STemp_default_longwave_reflect_fraction: 0.0
STemp_default_cloud_fraction: 0.1
STemp_default_emissivity_veg: 0
STemp_default_shade_fraction_riparian: 0.5
STemp_default_albedo: 0.1
STemp_default_delta_Z: 1.0       # for streambed conduction

params_water_density: 1000
params_C_w: 4184    # J/kg. K
NEARZERO: 1e-10
Epan_coef: 1.0

initial_values_shade_fraction: 0.1
no_basins: 20
potet_module: "potet_hamon"
srunoff_module: "srunoff_smidx"   # the nonlinear method, "srunoff_carea" linear method
Dprst_flag: 1      # Dprst_flag = 1 means depression storage simulation is computed ( 0= no, 1 = yes)
static_params_list_SNTEMP: [0,1,2,3,4,7, 8, 9,10,11,12, 13]
semi_static_params_list_SNTEMP: []
method_for_semi_static_param_SNTEMP: ["average", "average", "average", "average"]
interval_for_semi_static_param_SNTEMP: [5, 5]
static_params_list_prms: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17, 18, 19]
semi_static_params_list_prms: []
method_for_semi_static_param_prms: ["average", "average", "average", "average"]
interval_for_semi_static_param_prms: [30, 30]
SNTEMP_paramCalLst: [
            [0, 1],                                                    # rip shade factor
            [0, 1],                                                           # topo shade factor
            [0.0001, 25],                                                           # width A coefficient
            [0.0001, 0.25],                                                            # width power coefficient
            [0.004, 0.008],                        # PET_ hamon coefficient
            [0.01, 1], [0.01, 1],#        # flow portions
]
SNTEMP_lat_adj_paramCallLst: [
[-3, 5]                            # lateral temp adjusment
]
marrmot_paramCalLst: [
    [-3, 5],    # tt, Temperature threshold for snowfall and melt [oC]
    [0, 20],    # ddf,  Degree-day factor for snowmelt [mm/oC/d]
    [0, 1],     # alpha, Fraction of rainfall on soil moisture going to interception [-]
    [0, 1],    # beta, Fraction of catchment where rain goes to soil moisture [-]
    [0, 5],    # stor, Maximum interception capcity [mm]
    [0, 50],    # retip, Maximum impervious area storage [mm]
    [0, 1],    # fscn, Fraction of SCX where SCN is located [-]
    [0, 1],    # scx, Maximum contributing fraction area to saturation excess flow [-]
    [0.005, 0.995],    # flz, Fraction of total soil moisture that is the lower zone [-]
    [1, 2000],    # stot, Total soil moisture storage [mm]: REMX+SMAX
    [0, 20],    # cgw, Constant drainage to deep groundwater [mm/d]
    [1, 300],    # resmax, Maximum flow routing reservoir storage (used for scaling only, there is no overflow) [mm]
    [0, 1],    # k1, Groundwater drainage coefficient [d-1]
    [1, 5],    # k2, Groundwater drainage non-linearity [-]
    [0, 1],    # k3, Interflow coefficient 1 [d-1]
    [0, 1],    # k4, Interflow coefficient 2 [mm-1 d-1]
    [0, 1],    # k5, Baseflow coefficient [d-1]
    [0, 1],    # k6, Groundwater sink coefficient [d-1],
]
routing_PRMS: True
routing_SNTEMP: True
conv_SNTEMP: [
  # [0.01, 9], [0.01, 5], [0.01, 9], [0.01, 5], [0.01, 9], [0.01, 5],      # a and b
   [ 0.01, 12 ], [ 0.01, 12 ], [ 0.01, 12 ], [ 0.01, 12 ],  # a (k) and b (theta)
  #            [0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5],  # a (k) and b (theta)
  # [0.5, 9], [0.5, 2], [0.5, 9], [0.5, 2], [0.5, 9], [0.5, 2],  # a (k) and b (theta)
]
conv_PRMS: [
    [0, 2.9],  # routing parameter a
    [0, 6.5]   # routing parameter b
]
