##### This is an example .yaml file for how you should make your config file
##### See below for what you need to have
##### Make sure the paths are correct. They are individual to your machine
randomseed: [0]   # None means random
Action: [0, 1]   # 0:Train,   1: Test
device: "cuda"
nmul: 1
dataset:
#  forcing_path: "//storage//work//fzr5082//PGML_STemp_results//inputs//forcing_10%_days_415sites_ccov.feather" #          no_dam_forcing_99%_days34sites.feather
#  attr_path: "//storage//work//fzr5082//PGML_STemp_results//inputs//attr_415_all_3.feather" #          no_dam_attr_temp99%_days34sites.feather
  forcing_path: "/scratch/fzr5082/PGML_STemp_results/inputs/forcing_10%_days_415sites_ccov.feather" #        forcing_10%_days_415sites_ccov.feather  no_dam_forcing_99%_days34sites.feather
  attr_path: "/scratch/fzr5082/PGML_STemp_results/inputs/attr_415_all_4.feather" #        attr_415_all_3.feather  no_dam_attr_temp99%_days34sites.feather
output:
  model: "//home//fzr5082//PGML_STemp_results//models//415_sites//SNTEMP_artlength"
  data: "//home//fzr5082//PGML_STemp_results//data"

optData:
  name: 'hydroDL.data.camels.DataframeCamels'
  subset: 'All'
  varT: ['dayl(s)', 'prcp(mm/day)', 'tmax(C)', 'tmin(C)', 'vp(Pa)','srad(W/m2)', '00060_Mean', "ccov"]

  varC: [
    'DRAIN_SQKM','STREAMS_KM_SQ_KM','STOR_NID_2009', 'FORESTNLCD06', 'PLANTNLCD06',
     'SLOPE_PCT', 'RAW_DIS_NEAREST_MAJ_DAM', 'STRAHLER_MAX', 'CLAYAVE', 'stream_length_artificial', 'PPTAVG_BASIN',   # "NHDlength_tot(m)"
     'ELEV_MEAN_M_BASIN',

    'PERDUN', 'RAW_DIS_NEAREST_DAM', 'RAW_AVG_DIS_ALL_MAJ_DAMS', 'STOR_NOR_2009','SILTAVE',
    'T_MIN_BASIN', 'T_MINSTD_BASIN', 'RH_BASIN',  'RAW_AVG_DIS_ALLDAMS',
    'ELEV_MAX_M_BASIN', 'ELEV_MIN_M_BASIN', 'MAJ_NDAMS_2009',
    'T_AVG_BASIN', 'T_MAX_BASIN','T_MAXSTD_BASIN',  'NDAMS_2009',

#    'PERDUN', 'RAW_DIS_NEAREST_DAM', 'RAW_AVG_DIS_ALL_MAJ_DAMS',     # Round1
#     'GRASSNLCD06', 'WOODYWETNLCD06', 'RIP100_DEV', 'RAW_AVG_DIS_ALL_MAJ_NPDES', 'STOR_NOR_2009','SILTAVE',
#    'FRAGUN_BASIN',  'CANALS_PCT', 'FRESHW_WITHDRAWAL', 'PCT_IRRIG_AG',
#    'ROADS_KM_SQ_KM', 'PADCAT1_PCT_BASIN', 'PADCAT2_PCT_BASIN',
#
#    'T_MIN_BASIN', 'T_MINSTD_BASIN', 'RH_BASIN',  'RAW_AVG_DIS_ALLDAMS',    # Round2
#     'MIXEDFORNLCD06', 'SHRUBNLCD06','EMERGWETNLCD06',
#    'ELEV_MAX_M_BASIN', 'ELEV_MIN_M_BASIN', 'MAJ_NDAMS_2009', 'MAJ_DDENS_2009','SANDAVE', 'SNOW_PCT_PRECIP',
#    'HYDRO_DISTURB_INDX', 'GEOL_REEDBUSH_DOM_PCT','POWER_NUM_PTS', 'POWER_SUM_MW', 'ARTIFPATH_MAINSTEM_PCT',
#
#    'HIRES_LENTIC_PCT','T_AVG_BASIN', 'T_MAX_BASIN','T_MAXSTD_BASIN',  'NDAMS_2009',    # Round3
#    'DEVNLCD06',  'BARRENNLCD06', 'DECIDNLCD06',  'EVERGRNLCD06',
#    'ELEV_MEDIAN_M_BASIN', 'ELEV_STD_M_BASIN', 'RAW_AVG_DIS_ALLCANALS', 'NPDES_MAJ_DENS', 'DDENS_2009',
#    'PERHOR', 'CONTACT', 'MAINSTEM_SINUOUSITY', 'REACHCODE',
#    'ARTIFPATH_PCT','TOPWET', 'BAS_COMPACTNESS', 'AWCAVE', 'PERMAVE', 'RFACT'
  ]

  target: ["00010_Mean"]     # ['synth_T_1030365']   #   #     #['synth_shade_0130365']   ['synth_T_0520180']
#  tRange: [20101001, 20161001]
#  t_train: [20121001, 20151001]
#  t_val: [20151001, 20161001]
#  t_test: [20151001, 20161001]
  tRange: [19800101, 20200101]
  t_train: [20100101, 20141001]
  t_val: [20151001, 20161001]
  t_test: [20141001, 20160930]
  doNorm: [True, True]
  rmNan: [True, False]
  daObs: 0
  damean: False
  davar: 'StreamTemp'
  dameanopt: 0
  lckernel: None
  fdcopt: False
hyperparameters:
  rho: 365
  batch_size: 50
  EPOCHS: 400
  hidden_size: 256
  dropout: 0.5
  saveEpoch: 50
seq_lin_layers:
  hidden_size: 256
res_time_params:
  type: "Meisner"   #"van Vliet"  # "van Vliet", "Meisner", "SNTEMP"
  lenF_ssflow: 1   #60
  lenF_gwflow: 30 #
  lenF_srflow: 1
lat_temp_adj: "False"
shade_smoothening: "False"
frac_smoothening:
  mode: "True"
  gw_filter_size: 30
make_sr_masked_by_precip: "False"
params_target: ["res_time_srflow", "res_time_ssflow", "res_time_gwflow"]
one_param_target: ["shade_fraction"]
STemp_default_params:
  shade_fraction: 0.05
  longwave_reflect_fraction: 0.0
  cloud_fraction: 0.1
  emissivity_veg: 0
  shade_fraction_riparian: 0.5
  albedo: 0.1
  delta_Z: 1.0       # for streambed conduction
params:
  water_density: 1000
  C_w: 4184    # J/kg. K
NEARZERO: 1e-10
initial_values:
  shade_fraction: 0.1
no_basins: 415
params_calibrated:
  shade: "/home/fzr5082/PGML_STemp_results/params_calibrated/shade.pt"
potet_module: "potet_hamon"
static_params_list: [0,1,2,3,4,5,15]
semi_static_params_list: []
method_for_semi_static_param: ["average", "average", "average", "average"]
interval_for_semi_static_param: [30, 30]
paramCalLst: [
            # [0.01, 9], [0.01, 5], [0.01, 9], [0.01, 5], [0.01, 9], [0.01, 5],      # a and b
            [0.1, 5], [0.1, 5], [0.01, 0.011], [3, 3.01], [0.01, 0.011], [3, 3.01],  # a (k) and b (theta)
#            [0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5],  # a (k) and b (theta)
            # [0.5, 9], [0.5, 2], [0.5, 9], [0.5, 2], [0.5, 9], [0.5, 2],  # a (k) and b (theta)
            [0, 1],                                                    # rip shade factor
            [0.01, 1], [0.01, 1], [0.01, 1],                                    # flow portions
#            [0.06, 0.85], [0.06, 0.85], [0.12, 0.88],                          # flow portions
            # [-2, 2], [-2, 2], [-2, 2],                                 # conv bias
            # [0, 3], [-4, 4],                                            # final scale and final bias
            # [0.1, 0.10001],                                                        # albedo
            [0, 1],                                                           # topo shade factor
            [0.1, 4] , #[0.01, 2],                                            # width coefficient nominator
            # [0.01, 1],                                                         # width exponent
            # [0.01, 1],                                                            # width A coefficient
            [0.1, 1], #[0.5, 10], #[0.01, 1],                                  # width coefficient denominator
            # [0.01, 40],                                                    # p
            # [0.01, 2],                                                        # q
            # [-1, 1],                     # correction factor for T_0 ()temp of water at beginning in lateral flow
            # [0.01, 1],                       # cloud cover fraction
            [0.004, 0.008],                        # PET_ hamon coefficient
            [0, 1],                             # shading
            [-3, 5]
]
